version: "3.9"

# services:
#   # mysql:
#   #   image: mysql:5.7
#   #   container_name: godockerDB
#   #   restart: always
#   #   networks:
#   #     - my-network
#   #   volumes:
#   #     - subculture_ranking_mysql:/var/lib/mysql
#   #   environment:
#   #     MYSQL_ROOT_PASSWORD: secret
#   #     MYSQL_DATABASE: subculture_ranking
#   #   ports:
#   #     - "3306:3306"

#   # 今回は postgres をサービスとして定義しました。
#   postgres:
#     # Docker Image は postgres:12-alpine を使います。postgres:12-alpine は postgres:12 と比較して、イメージサイズが小さくなっています。
#     image: postgres:14
#     # コンテナの名前を指定します。
#     container_name: postgres
#     # 環境変数を設定します。
#     environment:
#       POSTGRES_HOST: db
#       POSTGRES_USER: root
#       POSTGRES_PASSWORD: secret
#       POSTGRES_DB: mydb
#       POSTGRES_HOST_AUTH_METHOD: trust
#     # データの永続化
#     volumes:
#       # postgresディレクトリを/var/lib/postgresql/dataにマウントする
#       - subculture_ranking_mysql:/var/lib/postgresql/data
#     # ポートの指定（HOST:CONTAINER）
#     ports:
#       - 5432:5432



#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     restart: always
#     # networks:
#     #   - my-network
#     ports:
#       - 8000:8000
#     depends_on:
#       - postgres
#     working_dir: /app
#     volumes:
#       - ./:/app
#     environment:
#       MYSQL_HOST: godockerDB
#       MYSQL_USER: root
#       MYSQL_PASSWORD: secret
#       MYSQL_DB: subculture_ranking
#       TMDBAPI: 6142e6f53164320f6e980f04a8c92884

# # データの永続化
# volumes:
#   subculture_ranking_mysql:
# # networks:
# #   my-network:
# #     driver: bridge

services:
  # front:
  #   build:
  #     dockerfile: Dockerfile.front
  #   volumes:
  #     - ./front:/app
  #   ports:
  #     - "8080:8000"
  #   tty: true
  #   environment:
  #     NODE_ENV: development
  #     BASE_URL: http://localhost:3030

  api:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./back:/app
    ports:
      - "3030:3000"
    depends_on:
      - db
    tty: true
    environment:
      POSTGRES_DB: gakusai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      TZ: "Asia/Tokyo"

  db:
    image: postgres:14
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: gakusai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      TZ: "Asia/Tokyo"
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  postgres_volume: